=== qetlife/4-In-A-Row-Web/src/main/webapp/xml/Users.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Users">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="user" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
            	<xs:element name="nickname" maxOccurs="1">
            		<xs:complexType>
            			<xs:simpleContent>
            				<xs:extension base="xs:string">
            					<xs:attribute name="losses"
            						type="xs:string" use="required" />
            					<xs:attribute name="time"
            						type="xs:string" use="required" />
            					<xs:attribute name="wins"
            						type="xs:string" use="required" />
            				</xs:extension>
            			</xs:simpleContent>
            		</xs:complexType>
            	</xs:element>
            	<xs:element name="password" maxOccurs="1">
            		<xs:simpleType>
            			<xs:restriction base="xs:string">
            				<xs:minLength value="3"></xs:minLength>
            				<xs:maxLength value="15"></xs:maxLength>
            			</xs:restriction>
            		</xs:simpleType>
            	</xs:element>
            	<xs:element name="nationality" type="xs:string"
            		maxOccurs="1" />
            	<xs:element name="age" maxOccurs="1">
            		<xs:simpleType>
            			<xs:restriction base="xs:string">
            				<xs:pattern value="\d+"></xs:pattern>
            			</xs:restriction>
            		</xs:simpleType>
            	</xs:element>
            	<xs:element name="picture" type="xs:string"
            		maxOccurs="1" />
            	<xs:element name="color" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== qetlife/4-In-A-Row-Web/src/main/webapp/xml/Users.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Users.xsd">
	<user>
		<nickname losses="9" time="342" wins="13">Roman</nickname>
		<password>bola</password>
		<nationality>Portugal</nationality>
		<age>24</age>
		<picture>/Users/roman/Desktop/d.pdf</picture>
		<color>#91cec4</color>
	</user>
	<user>
		<nickname losses="14" time="229" wins="4">Eduardo</nickname>
		<password>qwerty</password>
		<nationality>Afghanistan</nationality>
		<age>15</age>
		<picture>/Users/roman/Desktop/d.pdf</picture>
		<color>#428b25</color>
	</user>
	<user>
		<nickname losses="0" time="0" wins="0">qweq</nickname>
		<password>sad</password>
		<nationality>Andorra</nationality>
		<age>23</age>
		<picture/>
		<color>#428b25</color>
	</user>
	<user>
		<nickname losses="0" time="20" wins="2">Andre</nickname>
		<password>123</password>
		<nationality>Armenia</nationality>
		<age>30</age>
		<picture>/Users/roman/Desktop/GoToGate_FB volta.html</picture>
		<color>#428b25</color>
	</user>
	<user>
		<nickname losses="0" time="9" wins="1">LOL</nickname>
		<password>1212</password>
		<nationality>Uruguay</nationality>
		<age>22</age>
		<picture>/Users/roman/Desktop/GoToGate_FB volta.html</picture>
		<color>#428b25</color>
	</user>
	<user>
		<nickname losses="1" time="39" wins="1">teste</nickname>
		<password>zxcv</password>
		<nationality>Israel</nationality>
		<age>50</age>
		<picture>/Users/roman/Desktop/Hor√°rio ISEl</picture>
		<color>#428b25</color>
	</user>
</Users>
